name: Create env file

on:
  push:
    branches: [ main ]

jobs:
  creat_env_file:
    runs-on: ubuntu-latest

    steps:
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DEBUG: True
          envkey_DB_TYPE: "PROD"
          envkey_PROD_DATABASE_NAME: "DB"
          envkey_PROD_DATABASE_USER: "User"
          envkey_PROD_DATABASE_PASS: "Password"
          envkey_PROD_DATABASE_HOST: "db_host"
          envkey_PROD_DATABASE_PORT: "db_port"
          file_name: .env